AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 8
  MaxOptionalParameters: 8

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/OneClassPerFile:
  Exclude:
    - spec/spec_helper.rb
